FILES = Buffer.java Producer.java Consumer.java ProducerConsumer.java 
JFLAGS = -g
all:
	javac $(JFLAGS) $(FILES)
clean:
	rm *.class
package:
	zip -r VASILCHENKO-BOGDAN-HW4.zip $(FILES) Makefile README.txt
